#name of the workflow
name: .Net


#
#Specifies the trigger for this workflow
#will trigger on the master branch for push and pull request
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
      
#Jobs are the set of steps which are setup in the same runner 
      
jobs:
  build:
#will be built on Ubuntu os by taking default os version

    runs-on: self-hosted
#checkout of sourcecode

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      #setting up dotnet env
      with:
        dotnet-version: 3.1.101
        #Building project
 
      
